Fix vet_specialties
The DDL of `vet_specialties` is:

```sql
create table vet_specialties (
    specialty_id bigint not null,
    vet_id bigint not null,
    primary key (specialty_id, vet_id)
)
```

The `import.sql` was creating tuples of `(vet_id, specialty_id)`, causing the following exception on startup:

```text
org.postgresql.util.PSQLException: ERROR: insert or update on table "vet_specialties" violates foreign key constraint "fk35uiboyrpfn1bndrr5jorcj0m"
  Detail: Key (specialty_id)=(1004) is not present in table "specialties".
```